### ISSUE TITLE
Check if DB exists before trying to initialize its shell.

### ISSUE THREAD

**Issue by luisfvieirasilva** [tursodatabase/turso-cli#451]
Right now, when trying to connect to an invalid URL that has  `turso.io` domain it tries for a long time to connect, eventually reaches the timeout and returns the same thing: 
```
go run ./cmd/turso/main.go db shell libsql://asdfasd.turso.io                                                            
Error: failed to connect to database
```

To avoid this, if the shell encounters a turso.io hostname, it should check to make sure the db exists first before connecting.

This issue is the result of the discussion that started in [this](https://github.com/chiselstrike/turso-cli/issues/401) other one

**Comment by CodingDoug** [comment]
Also noting here that these lines of code:

https://github.com/chiselstrike/turso-cli/blob/main/internal/cmd/db_shell.go#L148-L150

Likely allow invalid hostnames that contain a suffix of an existing database hostname.  For example a database with hosting, `foo.turso.io` receives CLI connections targeting `libsql://other-stuff-foo.turso.io` since the actual hostname is a suffix of the provided hostname in the URL.

**Comment by notrab** [comment]
Looks to be resolved. Closing.
