### ISSUE TITLE
Cannot access CLI from Fish shell

### ISSUE THREAD

**Issue by falcon-Z** [tursodatabase/turso-cli#698]
I'm having an issue with running turso from fish shell. When I type `turso` in fish, I get `turso: command not found`. However, when I switch to bash shell, turso works fine and shows the expected output. Here is the transcript of my terminal session:

```shell
# Fish

me at Work in ~/projects
↪ turso 
 turso: command not found
me at Work in ~/projects
↪ bash

# Bash

me@Work:~/projects> turso
Turso CLI

Usage:
  turso [command]

Available Commands:
  auth        Authenticate with Turso
  config      Manage your CLI configuration
  contact     Reach out to the makers of Turso for help or feedback
  db          Manage databases
  dev         starts a local development server for Turso
  group       Manage your database groups
  help        Help about any command
  org         Manage your organizations
  plan        Manage your organization plan
  quickstart  Turso quick quickstart.
  relax       Sometimes you feel like you're working too hard... relax!
  update      Update the CLI to the latest version

Flags:
  -c, --config-path string                  Path to the directory with config file
  -h, --help                                help for turso
      --no-multiple-token-sources-warning   Don't warn about multiple access token sources
  -v, --version                             version for turso

Use "turso [command] --help" for more information about a command.
```

**Comment by athoscouto** [comment]
It doesn't look like a `turso` problem because fish doesn't even find the binary.

I'm not aware of fish internals, but I'd start debugging this by taking a look at your `$PATH` variable in both shells.
What probably is happening is that you've added the folder in which `turso` is installed to your `PATH` on some scrip that only bash runs (e.g. `.bashrc`).
You can find `turso` path by running `which turso` on bash.
You should also add it to some script fish runs on startup.

Let me know if that helps!
I'll close the issue, but feel free to reopen if you can't move forward or find more info.
