### ISSUE TITLE
Failed to connect to database when trying to open shell

### ISSUE THREAD

**Issue by lud-hu** [tursodatabase/turso-cli#759]
Hi everyone,

Last week or so it worked quite fine but now I cannot connect to my remote turso db anymore. I've updated the turso cli but I still get a `Error: failed to connect to database. err: failed to execute SQL: SELECT 1;` error.
I didn't change anything since last time, but the cli as well as the libsql lib cannot open the db anymore.
The localhost as well as the remote studio is not working anymore as well.

```sh
$ turso db list
NAME                  LOCATIONS         URL                                        
mydb     fra (primary)     libsql://mydb-myaccount.turso.io     
$ turso db shell mydb
Error: failed to connect to database. err: failed to execute SQL: SELECT 1;
Post "https://mydb-myaccount.turso.io/v2/pipeline": EOF
$ turso --version
turso version v0.87.7
```

Merry Christmas!

**Comment by notrab** [comment]
Hey @lud-hu 

I'm able to connect to a database on my personal and org accounts. It's likely there is an issue with the database itself.

Can you try to create another database and `shell` into that to confirm it's an issue with one database? If the issue persists, let me know and we can debug further. 

Are you able to `.dump` the database at all using the shell? `turso db shell mydb .dump > dump.sql`? Might be worth inspecting that.

I'll close this issue since it appears db related (if drizzle studio isn't loading either on the web).
